version: '3'
services:
  rna-web:
    build: .
    command: bash -c "bundle install && rm -f tmp/pids/server.pid && bundle exec rails s -p 3005 -b '0.0.0.0'"
    env_file:
      - .env.development
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
    networks:
      - ocf_collab
    ports:
      - 3005:3005

networks:
  ocf_collab:
    name: ocf_collab

volumes:
  bundle:
  node_modules:
